* Options                                                  :ARCHIVE:noexport:
#+SETUPFILE: ~/.config/orgmode/readthedocs.config
#+TITLE: Readme
#+SUBTITLE: Readme for dotfiles installation.
#+PROPERTY: header-args :exports none :results none :noweb yes
#+OPTIONS: author:nil date:nil timestamp:nil num:nil
#+CALL:
#+STARTUP: show2levels indent


* dotfiles
Dotfiles needs some place to stay.
Scrips and shell-settings that are useful. Mostly stolen goods, if you cant write steal with pride.

Moving to a =chezmoi= managed installation, since it was a bit tricky to maintain dotfiles on many devices with various configs. And want to use the same dotfiles directory for both Windows and Linux was an obstacle. But [[https://www.chezmoi.io/][Chezmoi]] seems to be the right tool for this.
Currently in =dev= status.

** Install
*** Linux
#+begin_src shell
sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "${HOME}/bin"
mkdir -p "${HOME}/.local/share"
chezmoi init --branch chezmoi --verbose sdaaish
#+end_src
*** Windows
#+begin_src powershell
New-Item -Path $HOME -Name .local/share -ItemType Directory
New-Item -Path $HOME -Name bin -ItemType Directory
(irm -useb https://get.chezmoi.io/ps1) | powershell -c -
chezmoi init --branch chezmoi --verbose sdaaish
#+end_src

**** Git and WSL
To use git with WSL and not need to have an extra SSH key, use Git Credential Manager (GCM). This was released as GCM Core initially but has since then removed the =-core= extension.

And use the Windows SSH_Agent that has the keys, and forward the requests with =npiperelay= so can SSH also work with minimum setup.
#+begin_src gitconfig
[credential]
	helper = /c/Program\\ Files/Git/mingw64/bin/git-credential-manager.exe

#+end_src
/NOTE/
=git-credential-manager.exe= was called =git-credential-manager-core.exe= in an earlier version of Git for Windows, so better check your version of git.

** Links
http://wiki.bash-hackers.org/

** Fonts
Need to install fonts with =get-nerd-fonts= before they are working with xterm.

[[www.futurile.net/2016/06/14/xterm-setup-and-truetype-font-configuration/]]
