#!/usr/bin/env bash
# -*- mode: bash; -*-

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

[ -f /etc/os-release ] &&  OS_VERSION=$(awk -F= '/VERSION_ID/{gsub("\"","",$2);print $2}' /etc/os-release)
export OS_VERSION

# To test with shellcheck, run with:
##  shellcheck -x -P $(pwd) .bashrc

# Set default umask
umask 027

# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return;;
esac

# load shell dotfiles
for file in "${HOME}"/.config/bash/{aliases,functions,exports}
do
    # shellcheck source=/dev/null # Ignore SC1090, SC1091 for these files
    source "${file}"
done

#
## HISTORY stuff
#

# Keep home clean
HISTFILE="${HOME}/.cache/custom/history"

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend
shopt -s cmdhist

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=5000
HISTFILESIZE=10000

# Correct spelling
shopt -s cdspell

# From https://www.digitalocean.com/community/tutorials/how-to-use-bash-history-commands-and-expansions-on-a-linux-vps
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# Disable Ctrl-S
stty -ixon

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]
then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]
then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null
    then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]
then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\u@\h:${WSL_DISTRO_NAME}\[\033[00m\]:\[\033[01;34m\]\w\n\$\[\033[00m\] '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\n\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
    xterm*|rxvt*)
        PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
        ;;
    dumb*)
        PS1="$ "
        ;;
    *)
        ;;
esac

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix
then
    if [ -f /usr/share/bash-completion/bash_completion ]
    then
        # shellcheck disable=SC1091
        source /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]
    then
        # shellcheck disable=SC1091
        source /etc/bash_completion
    fi
fi

# Completion for pip
compfile="${HOME}/.config/bash/pip-completion.bash"
if [ -f "${compfile}" ]
then
    # shellcheck source=.config/bash/pip-completion.bash
    source "${compfile}"
fi

# Completion for Chezmoi
compfile="${HOME}/.config/bash/chezmoi-completion.sh"
if [ -f "${compfile}" ]
then
    # shellcheck source=.config/bash/chezmoi-completion.sh
    source "${compfile}"
fi

# From https://github.com/chriskempson/base16-shell
BASE16_SHELL="${HOME}/.config/base16-shell/"
[ -n "$PS1" ] && [ -s "$BASE16_SHELL/profile_helper.sh" ] && eval "$("${BASE16_SHELL}/profile_helper.sh")"

# Use starship as prompt, https://starship.rs
[[ -x "$(command -v starship)" ]] && eval "$(starship init bash)"

# Use zoxide if it exists
[[ -x "$(command -v zoxide)" ]] && eval "$(zoxide init bash)"

# Use trigger sequence for FZF
[[ -x "$(command -v fzf)" ]] && eval "$(fzf --bash)"

# Completions for GitHub CLI
[[ -x "$(command -v gh)" ]] && eval "$(gh completion --shell bash)"

# Attach to tmux if running (and is installed), start it otherwise as a new session
# And don't start if inside Emacs using Eat
if [[ -x $(command -v tmux) ]] && [[ -z "${INSIDE_EMACS+x}" ]]
then
    if [[ $(pgrep tmux) ]]
    then
        # If we are in the session, dont start a new session, otherwise attach to it
        [[ -z ${TMUX} ]] 2>&1 >/dev/null && tmux new-session -A -s default || echo "Reused the TMUX session" >/dev/null
    else
        # Tmux is not running, start a new session
        tmux new-session -s default
    fi
fi

# Load direnv in the shell
[[ -x $(command -v direnv) ]] && eval "$(direnv hook bash)"
