#!/usr/bin/env bash
# -*- mode: bash; -*-

# Don't import anything if this is non-interactive
[[ $- == *i* ]] || return 0

# Source everything from .bashrc
# shellcheck source=.bashrc
[[ -f "$HOME"/.bashrc ]] && source "$HOME"/.bashrc
