(deftheme Homestead
  "Created 2021-06-14.")

(custom-theme-set-faces
 'Homestead
 '(default ((t (:inherit nil :extend nil :stipple nil :background "dim gray" :foreground "beige" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 102 :width normal :foundry "outline" :family "Cascadia Code"))))
 '(cursor ((t (:background "thistle"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#96a6c8"))))
 '(highlight ((t (:inverse-video nil :foreground "white" :background "dark green"))))
 '(region ((t (:extend t :foreground "white" :background "dark green"))))
 '(shadow ((t (:foreground "#52494e"))))
 '(secondary-selection ((t (:extend t :background "dark slate gray"))))
 '(trailing-whitespace ((t (:underline nil :inverse-video t :foreground "#000000" :background "#f43841"))))
 '(font-lock-builtin-face ((((class grayscale) (background light)) (:weight bold :foreground "LightGray")) (((class grayscale) (background dark)) (:weight bold :foreground "DimGray")) (((class color) (min-colors 88) (background light)) (:foreground "dark slate blue")) (((class color) (min-colors 88) (background dark)) (:foreground "LightSteelBlue")) (((class color) (min-colors 16) (background light)) (:foreground "Orchid")) (((class color) (min-colors 16) (background dark)) (:foreground "LightSteelBlue")) (((class color) (min-colors 8)) (:weight bold :foreground "blue")) (t (:weight bold))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#cc8c3c"))))
 '(font-lock-comment-face ((t (:foreground "SpringGreen3"))))
 '(font-lock-constant-face ((t (:foreground "turquoise"))))
 '(font-lock-doc-face ((t (:foreground "#73c936"))))
 '(font-lock-function-name-face ((t (:foreground "pale green"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "white"))))
 '(font-lock-negation-char-face ((t (:foreground "#4dd0e1"))))
 '(font-lock-preprocessor-face ((t (:foreground "#95a99f"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#fff59d"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#b39ddb"))))
 '(font-lock-string-face ((t (:foreground "dark khaki"))))
 '(font-lock-type-face ((t (:foreground "aquamarine"))))
 '(font-lock-variable-name-face ((t (:foreground "yellow green"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#f43841"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "cyan"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "dark cyan"))))
 '(fringe ((t (:foreground "#453d41" :background "#101010"))))
 '(header-line ((t (:foreground "#b39ddb" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#ffffff" :background "#52494e"))))
 '(mode-line ((t (:foreground "#ffffff" :background "#282828"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#ffffff" :background "#282828"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#ffffff"))))
 '(mode-line-highlight ((t (:box nil :foreground "#b39ddb"))))
 '(mode-line-inactive ((t (:weight normal :box nil :foreground "#95a99f" :background "#282828" :inherit (mode-line)))))
 '(isearch ((t (:foreground "white" :background "dark goldenrod"))))
 '(isearch-fail ((t (:inverse-video t :foreground "#000000" :background "#f43841" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:inverse-video nil :foreground "#263238" :background "gray25"))))
 '(match ((t (:inverse-video nil :foreground "#263238" :background "#52494e"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'Homestead)
