#!/usr/bin/env bash
# -*- mode: bash; -*-

#
# Alias file
#

# Remove old aliases
unalias emx &>/dev/null

# List alias
alias dmesg='dmesg -T --color=always| less -R'
alias l='less'
alias la='ls -la'
alias ll='ls -lAhG'
alias llt='ls -ltrah'
alias llh='ls -lah'
alias lls='ls -lAhSrG'
alias lll='find-links'
alias rehash='hash -r'
alias poff='sudo shutdown --poweroff now'
alias poffr='sudo shutdown --reboot now'

# Stupid stuff
alias sl='sl -ea'
alias sudp='sudo'

# Change dir
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias cdh='cd ~'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    #test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Git stuff
alias gta='git alias'
alias gtd='git diff'
alias gtr='git log --graph'
alias gts='git status -sb'
alias gtss="git status -sb --ignore-submodules=dirty"
alias gtp='git push && git pull'
alias glog="\git log --color --all --date-order --decorate --dirstat=lines,cumulative --stat | sed 's/\([0-9] file[s]\? .*)$\)/\1\n_______\n-------/g' | \less -R"

# emacs support
alias em='emacsclient -t -a ""'
alias ems='sudo emacsclient -t -a ""'
alias emdi='emacs --debug-init'
alias emd='emacs --daemon &>~/tmp/emacs-daemon.log &'
alias emk='emacsclient --eval "(save-buffers-kill-emacs)" --no-wait'
alias emfg='emacs --fg-daemon --debug-init'
alias emq='emacs -Q \
--border-color "White smoke" \
--background-color "LightSkyBlue1" \
--foreground-color "black" \
--cursor-color "DarkBlue" \
--no-blinking-cursor \
--eval "(progn (setq visible-bell t ring-bell-function (quote ignore))(toggle-frame-fullscreen)(toggle-tool-bar-mode-from-frame))"'

alias doom='~/.config/emacs/bin/doom'

if [[ (${OS_VERSION} == "20.04") || (${OS_VERSION} == "11") ]]
then
    alias mg='mg -n'
else
    alias mg='mg -n -u ~/.config/mg/config'
fi

# binary support
alias bbk='bbk_cli'
alias ff='firefox -P'

# system stuff
alias myver='lsb_release -a'

# Other stuff
alias kb='keybase'

# Certificate stuff
alias ov="openssl verify"
alias o5="openssl x509 -text -noout"

# Tools
alias psa="ps auxfww"
alias e="env|sort"

# Docker
alias dk="docker"
alias dco="docker compose"

# Kubernetes
alias k="kubectl"
alias nk="nerdctl"

# Python
alias python=python3
alias pip=pip3

# Code
alias ci='code-insiders'

# rclone GUI
alias rcgui='rclone rcd --rc-web-gui'

# systemd
alias sysu="systemctl --user"

# Chezmoi
alias cm='chezmoi'
alias cmdiff='chezmoi git pull -- --autostash --rebase && chezmoi diff'

# APT
alias apu='apt list --upgradable'
